### ISSUE TITLE
Support CSRF check using `CsrfCookie`

### ISSUE THREAD

**Issue by Bricklou** [edward-shen/actix-csrf#1]
Since `CsrfHeader` exists, it would be interesting to have the possibility to check the cookie. For JavaScript SPA, it would be interesting to avoid cookies manipulation.

The code would look like this:
```rs
/// Validates a json endpoint that has a CSRF token.
#[post("/login")]
async fn login(
    _: Csrf<CsrfCookie>,
    json: Json<Request>,
) -> impl Responder {
    // ...
}
```

This way, no need to change headers or add the token inside the JSON object while making requests. (i.e. with fetch API)

**Comment by edward-shen** [comment]
Hey, I don't think that works. This crate implements CSRF protection via the Double-submit pattern. Only using cookies is not sufficient for CSRF protection.

**Comment by Bricklou** [comment]
Ok, then I will try to look how to submit the token from my app using headers (which use NextJS).
Thank you for your quick response.
