### ISSUE TITLE
Add support for actix-multipart

### ISSUE THREAD

**Issue by ghost** [edward-shen/actix-csrf#13]
Currently one cannot use [actix-multipart](https://docs.rs/actix-multipart/latest/actix_multipart/) together with this crate, since there is no `CsrfGuard` implementation on `actix-multipart`'s [`MultipartForm`](https://docs.rs/actix-multipart/latest/actix_multipart/form/struct.MultipartForm.html) extractor. It would be quite nice to be able to do this.

this would require #12 as a prerequisite due to an ahash version incompatibility.

**Comment by edward-shen** [comment]
To be clear, if #12 lands, this just needs a change in `Cargo.toml`:

```toml
actix-multipart = { version = "0.7", default_features = false, optional = true }
```

and a blanket impl in `extractor.rs`:

```rust
#[cfg(feature = "actix-multipart")]
impl<Inner> CsrfGuarded for actix_multipart::form::MultipartForm<Inner>
where
    Inner: CsrfGuarded + actix_multipart::form::MultipartCollect,
{
    #[inline]
    fn csrf_token(&self) -> &CsrfToken {
        (**self).csrf_token()
    }
}
```

right?

**Comment by ghost** [comment]
Exactly. 
I already have the code ready. 
I just wrote it in one go and split it into this and #12, to make the PRs more clear in purpose.
