### ISSUE TITLE
Custom `cookie_name` and `header_name`

### ISSUE THREAD

**Issue by Bricklou** [edward-shen/actix-csrf#2]
Hi,
Is it voluntary that `CsrfHeaderConfig::header_name` and `CsrfCookieConfig::cookie_name` attributes are not public?
I would like to configure custom names, but I didn't find any other way that using these 2 attributes to configure it.

https://github.com/edward-shen/actix-csrf/blob/47939fb6f0b64d2b045b4397387b559c4b2c21bb/src/extractor.rs#L58-L62

https://github.com/edward-shen/actix-csrf/blob/47939fb6f0b64d2b045b4397387b559c4b2c21bb/src/extractor.rs#L108-L112

Am I doing it wrong or is it a mistake?

**Comment by edward-shen** [comment]
You're correct. I never exposed these functions. I'll try and add this over the weekend.

**Comment by edward-shen** [comment]
Added. Let me know if you have any problems.
