### ISSUE TITLE
CSRF token missmatch error

### ISSUE THREAD

**Issue by newdev8** [edward-shen/actix-csrf#4]
Hello, thanks for adding the `Domain` header from the other issue, it really helped me!

Now, I have the following issue: I have a website on [example.com](example.com) and an endpoint on [api.example.com/v1](api.example.com/v1), When visiting [example.com](example.com) the CSRF cookie is set, but when making the request to [api.example.com/v1](api.example.com/v1) the server returns a `422 error`.

I have set the `Domain` param on the cookie to [.example.com](.example.com).

My CRSF token is set on the header, as my payloads are encrypted and I didn't manage to get it working otherwise.

Is there a way to fix this? Thanks.

**Comment by edward-shen** [comment]
To sanity check, can you post a raw request that you're sending to `api.example.com/v1`? Just to verify that you are sending a CSRF token with the same name that the API service is expecting? You should also be getting a warn message with tracing about a potential csrf attack. What does that warning say?

**Comment by newdev8** [comment]
The request is:
```
curl 'https://api.example.com/v1/' \
  -H 'authority: api.example.com' \
  -H 'accept: application/octet-stream' \
  -H 'accept-language: en,es;q=0.9,es-ES;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/octet-stream' \
  -H 'cookie: __Secure-Csrf-Token=1liqmhLqeguFeLkDSka33cYrbA4S5XwHBtLdtIZylr4' \
  -H 'csrf-token: 1liqmhLqeguFeLkDSka33cYrbA4S5XwHBtLdtIZylr4' \
  -H 'origin: https://example.com' \
  -H 'pragma: no-cache' \
  -H 'referer: https://example.com/' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Microsoft Edge";v="101"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53' \
  --data-raw $'\u0008\u0001\u0012\u0002\u0008\u0001' \
  --compressed
```

I do **not** receive any warning as output on the terminal.

**Comment by edward-shen** [comment]
Are you setting the log level correctly? If you are then it's the 422 isn't from actix-crsf then; since [actix-crsf always logs](https://github.com/edward-shen/actix-csrf/blob/master/src/lib.rs#L187) before returning a 422, and will helpfully indicate why it's returning a 422.

**Comment by newdev8** [comment]
But I only get the 422 when I have the header `_: Csrf<CsrfHeader>` in my function.

**Comment by edward-shen** [comment]
Okay, so that probably means you're not setting tracing's log level correctly then? Or are you getting logs from other modules?

**Comment by newdev8** [comment]
I am not getting logs from any other module.

**Comment by edward-shen** [comment]
Okay? Please set tracing's log level so we can figure it out?

**Comment by newdev8** [comment]
How do I set the log level?

**Comment by edward-shen** [comment]
Please read tracing's documentation: https://github.com/tokio-rs/tracing/tree/v0.1.x

**Comment by newdev8** [comment]
Okay, I'm receiving the following message now:
`WARN actix_csrf: Potential CSRF attack: The CSRF Tokens do not match`

**Comment by edward-shen** [comment]
Okay, that means that we're not finding the header or cookie, and since the header looks unchanged, I suspect the main reason is that it's looking for the wrong cookie. Did you add `CookieNameConfig` as app data?

**Comment by newdev8** [comment]
Sorry, what's `CookieNameConfig`?

**Comment by edward-shen** [comment]
Ah, sorry, I meant [`CrsfCookieConfig`](https://docs.rs/actix-csrf/latest/actix_csrf/extractor/struct.CsrfCookieConfig.html)

**Comment by newdev8** [comment]
What I have in my main app is:
`.wrap(CsrfMiddleware::<StdRng>::new().http_only(false).set_cookie(http::Method::GET, "/").domain(".example.com"))`

**Comment by edward-shen** [comment]
Ah, you'll need to use `CrsfCookieConfig`, otherwise it'll be looking for the default cookie name. See https://github.com/edward-shen/actix-csrf/blob/master/tests/custom_cookie_name.rs#L90-L98 for an example.

**Comment by newdev8** [comment]
I added `.cookie_name("__Secure-Csrf-Token")` to my function but it's still throwing the same warning.

**Comment by edward-shen** [comment]
You're not suppose to change that. I meant https://github.com/edward-shen/actix-csrf/blob/master/tests/custom_cookie_name.rs#L95

**Comment by newdev8** [comment]
It's working now! Thanks a lot!
